version: '3'

services:
  kitchenservice:
    image: tonymackay/demoservice:1.0.0
    restart: always
    environment:
      - APP_PORT=8081
      - APP_NAME=KitchenService
    ports:
      - "8081:8081"

  orderservice:
    image: tonymackay/demoservice:1.0.0
    restart: always
    environment:
      - APP_PORT=8082
      - APP_NAME=OrderService
    ports:
      - "8082:8082"
