---

version: "3"

networks:
  default:
    name: example.com

services:

  base:
    #image: quay.io/tonykay/vmlet-fedora-ansible-control
    image: vmlet-fedora-ansible-control
    container_name: ansible
    hostname: ansible
    ports:
      - "2222:22"
    privileged: true

...
