---

version: "3"

networks:
  default:
    name: example.com
      #        - subnet: 172.22.0.0/16


services:

  vmlet-rhel-8-base:
    container_name: vmlet-rhel-8-base
    hostname: vmlet-rhel-8-base
    image: vmlet-rhel-8-base
    ports:
      - "2222:22"
    privileged: true
#    networks:
#      default:
#        ipv4_address: 172.22.0.100
#
...

#version: '3.5'
#services:
#  service1:
#  image: service1:latest
#  networks:
#    service1_net:
#      ipv4_address: 172.22.0.100
#networks:
#  service1_net:
#    ipam:4Y
#      driver: default
#      config:
#        - subnet: 172.22.0.0/16
