# syntax = docker/dockerfile:1.0-experimental

ARG RHEL_VERSION
FROM registry.access.redhat.com/ubi8/ubi:${RHEL_VERSION:-latest}

LABEL maintainer="Tok - Tony Kay tony.g.kay@gmail.com"

ENV DEVOPS_USER=devops

RUN yum install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
        bind-utils \
        coreutils \
        curl \
        hostname \
        iputils \
        python3.8 \
        sudo \
    && useradd --uid 1000 devops \
    && pip3 --no-cache-dir install butterfly \
    && yum clean all \
    && rm -rf /var/cache/yum

EXPOSE 8080

USER devops

CMD ["butterfly.server.py", "--port=8080", "--host=0.0.0.0", "--unsecure", "--i-hereby-declare-i-dont-want-any-security-whatsoever"]
