---
# Simple ssh jumpbox example 

networks:
  default:
    name: example.com

services:

  control:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: control
    hostname: control
    privileged: true
    ports:
      - "2222:22"

  target:
    image: quay.io/tonykay/vmlet-rhel-8-base
    privileged: true

