---

envy_name:                    multi

envy_networks:
  - name:                     "{{ envy_default_domain | default('example.com') }}"
    #  - name:                     internal.com

    
envy_default_image:           vmlet-rhel7-target

envy_instances:

  - name: control
    group: control_node
    image: vmlet-rhel8-ansible
    volumes:
      - "{{ envy_local_home }}/shared_dir/:/home/{{ envy_ssh_user }}/shared_dir:z,rw"

  - name: terminal
    group: terminal
    image: quay.io/openshifthomeroom/workshop-terminal:latest
    published_ports:
      - "10080:10080"

  - name: antora
    group: control_node
    image: antora
    volumes:
      - "{{ envy_local_home }}/content/:/home/{{ envy_ssh_user }}/shared_dir:z,rw"

  - name: lab-webserver
    group: lab-webserver
    image: rhel-8-lab-webserver
    volumes:
      - "{{ envy_local_home }}/content/output:/var/www/html:z,rw"
    published_ports:
      - "81:80"

  - name: frontend1
    group: load_balancers
    published_ports:
      - "8080:80"

  - name: app1
    group: app_servers

  - name: app2
    group: app_servers

  - name: appdb1
    group: database_servers

...
