###  syntax # = docker/dockerfile:1.0-experimental

ARG ARCH
ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION:-latest}
#ARG REPO_ARCH=
#ENV REPO_ARCH=${REPO_ARCH:-x86_64}

# ssh, systemd, passwordless sudo container for ansible target use etc
#
# docker run --privileged -d -p 2222:22 --rm --name vmlet-rhel-8-base

LABEL maintainer="Tok - Tony Kay tony.g.kay@gmail.com"

ENV SSH_PORT=22
ENV SSH_USER=devops
ENV PYTHON_VERSION=38
# ENV SSH_KEY_NAME=devops

# These keys are "well known" vagrant keys - they are NOT for production use
# ENV SSH_PUBLIC_KEY_URL=https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
# ENV SSH_PRIVATE_KEY_URL=https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant

# 1) Install, configure, and enable sshd using *CentOS* RPM, RHEL RPM not distributable with ubi
# 2) Add a user and ssh public key 
# 3) Add EPEL? dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
# 4) OPTIONAL, enable passwordless sudo   


# Configure ssh keys AND add the password 'devops' for the devops user
COPY ssh_config_dir_resources/* /home/${SSH_USER}/.ssh/
COPY sshd_config/*  /etc/ssh

ENV SSH_USER_PASSWORD='$6$tWkgXG0kU57p7Rjc$ZCvOpW.oHLT0l6KEnk8CUW.o2OjP7vtnly8YbhXMd4ArugznNQFEwkpMR2S7hHLZxrjYIKFgCXLtBakh21Z4t0'

RUN rm -f /run/nologin \
    rm -f fedora-cisco-openh264.repo

EXPOSE ${SSH_PORT:-22}

COPY entrypoint.sh /entrypoint.sh
#ADD sshd_config /tmp/sshd_config

#COPY sshd_config/ssh/sshd_config /etc/ssh/sshd_config
#COPY sshd_config/ssh/ssh_config /etc/ssh/ssh_config
#COPY sshd_config/ssh/ssh_config.d/05-redhat.conf /etc/ssh/ssh_config.d/05-redhat.conf

# USER devops # Fix via sudo in CMD?

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/sbin/init"]

