# syntax=docker/dockerfile:1.2

ARG ARCH
ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION:-latest}

# sshd, systemd, passwordless sudo container for ansible target use etc
# docker run --privileged -d -p 2222:22 --rm --name vmlet-fedora-base

LABEL maintainer="Tok - Tony Kay tony.g.kay@ gmail.com"

ENV SSH_PORT=22
ENV SSH_USER=devops
ENV PYTHON_VERSION=38

# This image is NOT RECOMMENDED FOR PRODUCTION USE!
# It's intent is for labs, local mockup, PoCs etc where composing 5 webservers for example is useful
# in the developement process

# These keys are "well known" vagrant keys - they are NOT for production use
# ENV SSH_PUBLIC_KEY_URL=https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
# ENV SSH_PRIVATE_KEY_URL=https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant

# Add EPEL? dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
# OPTIONAL, enable passwordless sudo   


# Configure ssh keys AND set the password 'devops' for the devops user
# Configure sshd using a typical RHEL 8.4 config

COPY ssh_config_dir_resources/* /home/${SSH_USER}/.ssh/
COPY sshd_config/*  /etc/ssh

# The SSH_USER_PASSWORD is devops but full support for ssh keys is baked in
ENV SSH_USER_PASSWORD='$6$tWkgXG0kU57p7Rjc$ZCvOpW.oHLT0l6KEnk8CUW.o2OjP7vtnly8YbhXMd4ArugznNQFEwkpMR2S7hHLZxrjYIKFgCXLtBakh21Z4t0'

RUN rm -f /etc/yum.repos.d/fedora-cisco-openh264.repo \
    && dnf update -y \
    && dnf install -y \
      bind-utils \
      file \
      hardlink \
      hostname \
      iputils \
      iproute \
      less \
      libedit \
      ncurses \
      procps-ng \
      python${PYTHON_VERSION:-38} \
      openssh \
      openssh-clients \
      openssh-server \
      sudo \
      systemd \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key \
    && useradd --uid 1000 ${SSH_USER} \
    && mkdir -p /home/${SSH_USER}/.ssh \
    && chmod 600 /home/${SSH_USER}/.ssh/* \
    && chmod 700 /home/${SSH_USER}/.ssh \
    && chown -R ${SSH_USER}:${SSH_USER} /home/${SSH_USER} \
    && echo "${SSH_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && sed -i "s/^devops:\!\!/devops:${SSH_USER_PASSWORD}/" /etc/shadow \
    && rm -f /run/nologin \
    && dnf clean all \
    && rm -rf /var/cache/dnf /root/.cache \
    && (cd /lib/systemd/system/sysinit.target.wants/ ; for i in * ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i ; done) ; \
      rm -f /lib/systemd/system/multi-user.target.wants/* \
      rm -f /etc/systemd/system/*.wants/* \
      rm -f /lib/systemd/system/local-fs.target.wants/* \
      rm -f /lib/systemd/system/sockets.target.wants/*udev* \
      rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
      rm -f /lib/systemd/system/basic.target.wants/* \
      rm -f /lib/systemd/system/anaconda.target.wants/* \
    && systemctl enable --now sshd.service 

EXPOSE ${SSH_PORT:-22}

# RUN rm -f /run/nologin 

COPY entrypoint.sh /entrypoint.sh
#      systemd \
#    && echo "RSAAuthentication yes" >> /etc/ssh/sshd_config \
#   && echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config \
#ADD sshd_config /tmp/sshd_config

#COPY sshd_config/ssh/sshd_config /etc/ssh/sshd_config
#COPY sshd_config/ssh/ssh_config /etc/ssh/ssh_config
#COPY sshd_config/ssh/ssh_config.d/05-redhat.conf /etc/ssh/ssh_config.d/05-redhat.conf

# USER devops # Fix via sudo in CMD?

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/sbin/init"]
