---

version: "3"

networks:
  default:
    name: example.com

services:

  base:
    # image: quay.io/tonykay/vmlet-rhel-8-base
    image: vmlet-fedora-base
    container_name: base
    hostname: base
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ports:
      - "2222:22"
    privileged: true

...
