---

networks:
  default:
      name: example.com

services:

  lab-terminal:
    container_name: lab-terminal
    hostname: lab-terminal
    image: service-rhel-8-terminal-base 
    privileged: true
    ports:
      - "2223:22"           # Direct ssh access localhost 2222 devops/vagrant key
      - "10080:8888"        # Browser based terminal session

  lab-httpd:
    image: registry.redhat.io/rhel8/httpd-24
    container_name: lab-httpd
    hostname: lab-httpd
    volumes:
      - "./lab-html-content:/var/www/html:z,ro"
    privileged: true
    ports:
      - "80:8080"

  control:
    image: quay.io/tonykay/vmlet-rhel-8-ansible-control
    container_name: control
    hostname: control
    ports:
      - "2222:22"
    privileged: true
      #volumes:
      # - "../bind_mounts/ssh:/opt/app-root/src/.ssh:z,ro"
    
  frontend:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: frontend
    hostname: frontend
    ports:
      - "8080:80"
    privileged: true

  app-01:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: app-01
    hostname: app-01
    privileged: true

  app-02:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: app-02
    hostname: app-02
    privileged: true

  appdb1:
    image: quay.io/tonykay/vmlet-rhel-8-base
    container_name: appdb1
    hostname: appdb1
    privileged: true

...
