---

version: "3"

networks:
  default:
    name: example.com

services:

  base:
    #image: quay.io/tonykay/vmlet-fedora-ansible-control
    image: vmlet-fedora-init
    container_name: fedora
    hostname: fedora
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true

...
