---
- name: Add Red Hat Network Subscription
  hosts: all
  become: yes
  vars_files:

    - ~tok/secrets/rhel-subscription.yml

  tasks:

    - name: Setup base subscriptions and RHN
      block:    
        - name: Activate RHEL subscription
          redhat_subscription:
            activationkey:    "{{ rhel_activationkey }}"
            org_id:           "{{ rhel_org_id }}"   
            server_insecure:  true

...
